#!/usr/bin/env python3
"""Generates source/path_normalize_tables.odin (NFC normalization tables).

Run from the project root. Requires Python 3.3+ (unicodedata).
"""
import unicodedata

OUT = "source/path_normalize_tables.odin"

# Canonical decompositions (Hangul is composed arithmetically by the loader).
decomp = []  # (composed, base, mark), mark 0 for single-codepoint decompositions
for cp in range(0x110000):
    if 0xAC00 <= cp <= 0xD7A3:
        continue
    d = unicodedata.decomposition(chr(cp))
    if not d or d.startswith("<"):
        continue  # Hangul + compatibility forms are handled separately
    parts = d.split()
    a = int(parts[0], 16)
    b = int(parts[1], 16) if len(parts) == 2 else 0
    decomp.append((cp, a, b))

# Composition table keeps only pairs Python actually composes: characters in
# CompositionExclusions.txt decompose but never recompose.
comp = []
for cp, a, b in decomp:
    if b and unicodedata.normalize("NFC", chr(a) + chr(b)) == chr(cp):
        comp.append((a, b, cp))

marks = [(c, unicodedata.combining(chr(c))) for c in range(0x110000)
         if unicodedata.combining(chr(c)) != 0]

comp.sort()
decomp.sort()

with open(OUT, "w") as f:
    f.write("package game\n\n")
    f.write("// NFC normalization tables, generated by\n")
    f.write("// scripts/generate_normalize_tables.py (Unicode %s). Do not edit by hand.\n"
            % unicodedata.unidata_version)
    f.write("\nNfc_Pair :: struct {\n\tbase: u32,\n\tmark: u32,\n}\n\n")
    f.write("// Sorted by (base, mark); result at the same index in Nfc_Comp_Composed.\n")
    f.write("Nfc_Comp_Pairs := [%d]Nfc_Pair {\n" % len(comp))
    for base, mark, _ in comp:
        f.write("\t{0x%x, 0x%x},\n" % (base, mark))
    f.write("}\n\n")
    f.write("Nfc_Comp_Composed := [%d]u32 {\n" % len(comp))
    for _, _, cp in comp:
        f.write("\t0x%x,\n" % cp)
    f.write("}\n\n")
    f.write("// Sorted by composed; mark is 0 for single-codepoint decompositions.\n")
    f.write("Nfc_Decomp_Src := [%d]u32 {\n" % len(decomp))
    for src, _, _ in decomp:
        f.write("\t0x%x,\n" % src)
    f.write("}\n\n")
    f.write("Nfc_Decomp_Pairs := [%d]Nfc_Pair {\n" % len(decomp))
    for _, base, mark in decomp:
        f.write("\t{0x%x, 0x%x},\n" % (base, mark))
    f.write("}\n\n")
    f.write("// Sorted by codepoint.\n")
    f.write("Nfc_Mark_Class :: struct {\n\tcp:    u32,\n\tclass: u8,\n}\n\n")
    f.write("Nfc_Mark_Classes := [%d]Nfc_Mark_Class {\n" % len(marks))
    for cp, cls in marks:
        f.write("\t{0x%x, %d},\n" % (cp, cls))
    f.write("}\n")

print("wrote", OUT, "comp:", len(comp), "decomp:", len(decomp), "marks:", len(marks))
